export const MUTATIONS = {
    SET_MESSAGES: 'SET_MESSAGES',
    SET_NEXT_PAGE_TOKEN: 'SET_NEXT_PAGE_TOKEN',
    SET_CURRENT_PAGE_TOKEN: 'SET_CURRENT_PAGE_TOKEN',
    PUSH_PREV_PAGE_TOKEN: 'PUSH_PREV_PAGE_TOKEN',
    SET_CURRENT_MESSAGE: 'SET_CURRENT_MESSAGE',
    SET_API_STATUS: 'SET_API_STATUS',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    UPDATE_QUERY: 'UPDATE_QUERY'
}

export const ACTIONS = {
    AUTHENTICATE: 'AUTHENTICATE',
    LOAD_MESSAGES:'LOAD_MESSAGES',
    LOAD_NEXT_PAGE: 'LOAD_NEXT_PAGE',
    LOAD_PREV_PAGE: 'LOAD_PREV_PAGE',
    OPEN_MESSAGE: 'OPEN_MESSAGE',
    UPDATE_QUERY: 'UPDATE_QUERY',
    LOAD_ATTACHMENT: 'LOAD_ATTACHMENT'
}
