export const MUTATIONS = {
    SET_MESSAGES: 'SET_MESSAGES',
    SET_NEXT_PAGE_TOKEN: 'SET_NEXT_PAGE_TOKEN',
    SET_PREV_PAGE_TOKEN: 'SET_PREV_PAGE_TOKEN',
    SET_CURRENT_MESSAGE: 'SET_CURRENT_MESSAGE'
}

export const ACTIONS = {
    LOAD_MESSAGES:'LOAD_MESSAGES',
    LOAD_NEXT_PAGE: 'LOAD_NEXT_PAGE',
    LOAD_PREV_PAGE: 'LOAD_PREV_PAGE',
    OPEN_MESSAGE: 'OPEN_MESSAGE'
}
